///usr/bin/env java --source 21 "$0" "$@" ; exit $?
//
// ArchHook — project hooks in a single Java file.
//
// Why Java and not bash+PowerShell: this template targets Java developers,
// so the JDK is the only dependency that can be assumed on any operating system.
// Writing the logic twice (.sh and .ps1) would violate the "each rule has a single
// owner" rule this repository enforces everywhere else — and the two copies would drift.
//
// Execution (Java 11+, single-file source): java ArchHook.java <mode>
//   check   PostToolUse — forbidden imports + incremental compile     (blocks)
//   format  PostToolUse — spotless on the touched module              (never blocks)
//   tests   Stop        — tests of the changed modules                (blocks)
//   schema  Pre/PostToolUse + Stop — frontmatter of extension files   (blocks)
//   audit   lifecycle   — execution trail of the orchestrator skills  (never blocks)
//   doctor  manual      — diagnoses the setup on this machine         (never blocks)
//
// Dependencies: JDK. Nothing else.

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.time.Instant;
import java.util.*;
import java.util.regex.*;
import java.util.stream.*;

public class ArchHook {

    static final Path ROOT = Paths.get(
            Optional.ofNullable(System.getenv("CLAUDE_PROJECT_DIR")).orElse("."))
            .toAbsolutePath().normalize();
    static final boolean WINDOWS =
            System.getProperty("os.name", "").toLowerCase(Locale.ROOT).contains("win");

    /** Windows consoles default to cp1252: forcing UTF-8 avoids broken accented characters. */
    static final PrintStream ERR = new PrintStream(
            new FileOutputStream(FileDescriptor.err), true, StandardCharsets.UTF_8);

    public static void main(String[] args) throws Exception {
        String mode = args.length > 0 ? args[0] : "check";
        String stdin = readAll(System.in);
        try {
            switch (mode) {
                case "check"  -> check(filePath(stdin));
                case "format" -> format(filePath(stdin));
                case "tests"  -> tests(stdin);
                case "schema" -> schema(stdin);
                case "audit"  -> audit(args.length > 1 ? args[1] : "flush", stdin);
                case "doctor" -> doctor();
                default -> { err("Unknown mode: " + mode); System.exit(0); }
            }
        } catch (Exception e) {
            // A hook must never crash the session because of its own error.
            err("⚠️  ArchHook (" + mode + ") failed: " + e);
            System.exit(0);
        }
        System.exit(0);
    }

    // ── check ────────────────────────────────────────────────────────────────
    static void check(String file) throws Exception {
        if (file == null || !file.endsWith(".java")) return;
        Path abs = Paths.get(file);
        if (!Files.isRegularFile(abs)) return;
        String rel = relative(abs);

        // 1. forbidden imports
        Path map = ROOT.resolve(".claude/forbidden-imports.txt");
        if (Files.isRegularFile(map)) {
            String src = Files.readString(abs, StandardCharsets.UTF_8);
            List<String> viol = new ArrayList<>();
            for (String line : Files.readAllLines(map, StandardCharsets.UTF_8)) {
                line = line.strip();
                if (line.isEmpty() || line.startsWith("#")) continue;
                int bar = line.indexOf('|');
                if (bar < 0) continue;
                String module = line.substring(0, bar).strip();
                String prefix = line.substring(bar + 1).strip();
                if (prefix.isEmpty() || !rel.startsWith(module + "/")) continue;
                Pattern p = Pattern.compile(
                        "(?m)^\\s*import\\s+(static\\s+)?" + Pattern.quote(prefix));
                if (p.matcher(src).find()) {
                    viol.add("  " + prefix + "  (forbidden in module '" + module + "')");
                }
            }
            if (!viol.isEmpty()) {
                err("❌ Architectural boundary violation — " + rel);
                err("Forbidden imports found:");
                viol.forEach(ArchHook::err);
                err("");
                err("The responsibility is in the wrong module. Move the code, not the rule.");
                err("Rule: .claude/rules/architecture-ddd.md");
                System.exit(2);
            }
        } else {
            err("⚠️  .claude/forbidden-imports.txt does not exist.");
            err("   Boundary enforcement OFF — nothing was checked.");
            err("   This file is generated by /init-project from the active blueprint.");
        }

        // 2. incremental compile of the touched module
        String module = moduleOf(rel);
        if (module == null) return;                       // no POM yet: mid-generation
        String mvnw = wrapper();
        if (mvnw == null) {
            err("⚠️  Maven wrapper missing — compilation NOT checked.");
            err("   Run /init-project (starter.tgz already brings the mvnw).");
            return;
        }
        Proc r = run(mvnw, "-q", "-o", "-pl", module, "-am", "test-compile");
        if (r.exit != 0) {
            err("❌ Compilation failed in " + module);
            tail(r.out, 30).forEach(ArchHook::err);
            System.exit(2);
        }
    }

    // ── format ───────────────────────────────────────────────────────────────
    static void format(String file) throws Exception {
        if (file == null || !file.endsWith(".java")) return;
        Path abs = Paths.get(file);
        if (!Files.isRegularFile(abs)) return;
        String module = moduleOf(relative(abs));
        String mvnw = wrapper();
        if (module == null || mvnw == null) return;
        run(mvnw, "-q", "-o", "-pl", module, "spotless:apply");   // failure is ignored
    }

    // ── tests ────────────────────────────────────────────────────────────────
    static void tests(String stdin) throws Exception {
        // If the Stop hook already blocked before, don't block again: avoids cycles.
        if (Pattern.compile("\"stop_hook_active\"\\s*:\\s*true").matcher(stdin).find()) return;

        String mvnw = wrapper();
        if (mvnw == null) return;

        Proc diff = run(gitCmd(), "diff", "--name-only", "HEAD");
        Proc untracked = run(gitCmd(), "ls-files", "--others", "--exclude-standard");
        if (diff.exit != 0 && untracked.exit != 0) return;        // no git or no HEAD

        Set<String> modules = Stream.concat(diff.out.stream(), untracked.out.stream())
                .filter(f -> f.endsWith(".java"))
                .map(ArchHook::moduleOf)
                .filter(Objects::nonNull)
                .collect(Collectors.toCollection(LinkedHashSet::new));
        if (modules.isEmpty()) return;

        String list = String.join(",", modules);
        err("▶ Tests for affected modules: " + list);
        Proc r = run(mvnw, "-q", "-o", "-pl", list, "-am", "test");
        if (r.exit != 0) {
            err("❌ Tests failed");
            List<String> relevant = r.out.stream()
                    .filter(l -> l.matches(".*(ERROR|FAIL|Tests run).*"))
                    .collect(Collectors.toList());
            tail(relevant.isEmpty() ? r.out : relevant, 25).forEach(ArchHook::err);
            System.exit(2);
        }
        err("✅ Tests green");
    }

    // ── doctor ───────────────────────────────────────────────────────────────
    /** Answers "does this work on my machine?" without having to guess. */
    static void doctor() {
        err("ArchHook doctor");
        err("  OS ................ " + System.getProperty("os.name")
                + (WINDOWS ? "  (Windows — no shell is used, exec form)" : ""));
        err("  Java .............. " + System.getProperty("java.version"));
        err("  Project root ...... " + ROOT);
        report("CLAUDE_PROJECT_DIR", System.getenv("CLAUDE_PROJECT_DIR") != null,
                "set", "NOT set — hooks use the current directory");
        String w = wrapper();
        report("Maven wrapper", w != null, w == null ? "" : w,
                "missing — run /init-project (starter.tgz already brings the mvnw)");
        Path map = ROOT.resolve(".claude/forbidden-imports.txt");
        long rules = 0;
        try {
            if (Files.isRegularFile(map)) {
                rules = Files.readAllLines(map).stream()
                        .map(String::strip)
                        .filter(l -> !l.isEmpty() && !l.startsWith("#") && l.contains("|"))
                        .count();
            }
        } catch (IOException ignored) { }
        report("Boundaries", rules > 0, rules + " active rules",
                "0 rules — ENFORCEMENT OFF. Generated by /init-project");
        long badSchema = -1;
        if (Files.isRegularFile(ROOT.resolve(SCHEMA_FILE))) {
            List<String> errs = new ArrayList<>();
            try {
                sweep(asMap(Json.parse(readOrNull(ROOT.resolve(SCHEMA_FILE)))), errs);
                badSchema = errs.size();
            } catch (IOException ignored) { }
        }
        report("Schema", badSchema == 0,
                "all extension files pass",
                badSchema < 0 ? "no " + SCHEMA_FILE + " — validation OFF"
                              : badSchema + " files with invalid frontmatter");
        Path auditDir = ROOT.resolve(AUDIT_DIR);
        if (Files.isDirectory(auditDir)) {
            long runs = 0;
            try (Stream<Path> s = Files.list(auditDir)) {
                runs = s.filter(f -> f.toString().endsWith(".md")).count();
            } catch (IOException ignored) { }
            boolean priced = auditCost(new Tokens(1, 0, 0, 0, "probe")) != null
                    || Files.isRegularFile(auditDir.resolve("pricing.json"));
            report("Audit", true, runs + " execution(s) recorded"
                    + (priced ? "" : " — pricing.json missing, no cost estimate"), "");
        } else {
            err("  Audit ............. ⚪ no " + AUDIT_DIR + " — execution trail OFF (optional)");
        }

        Path mcpFile = ROOT.resolve(".mcp.json");
        if (Files.isRegularFile(mcpFile)) {
            List<String> mcpErrs = new ArrayList<>();
            Map<String, Object> schRoot = asMap(Json.parse(readOrNull(ROOT.resolve(SCHEMA_FILE))));
            String mcpContent = readOrNull(mcpFile);
            checkMcp(schRoot == null ? null : asMap(schRoot.get("mcp")), ".mcp.json",
                    mcpContent, mcpErrs);
            Map<String, Object> mcpRoot = asMap(Json.parse(mcpContent));
            Map<String, Object> servers = mcpRoot == null ? null : asMap(mcpRoot.get("mcpServers"));
            int n = servers == null ? 0 : servers.size();
            report("MCP", mcpErrs.isEmpty(), n + " server(s) declared in .mcp.json",
                    mcpErrs.size() + " problem(s) — run `java ArchHook.java schema`");
        } else {
            err("  MCP ................ no .mcp.json — nothing declared (optional)");
        }
        boolean git = false;
        try { git = run("git", "rev-parse", "HEAD").exit == 0; } catch (Exception ignored) { }
        report("git HEAD", git, "exists",
                "no commits — the tests hook does not run (git diff HEAD fails)");
        err("");
        err(rules > 0 && w != null
                ? "✅ Setup operational."
                : "⚠️  Setup incomplete — see marked lines above.");
    }

    static void report(String label, boolean ok, String yes, String no) {
        String pad = "                  ".substring(Math.min(label.length(), 17));
        err("  " + label + " " + pad.replace(' ', '.') + " " + (ok ? "✅ " + yes : "❌ " + no));
    }

    // ── schema ───────────────────────────────────────────────────────────────
    //
    // Guards the frontmatter fields of Claude Code's extension files.
    // The runtime silently ignores an unknown field and `claude plugin validate`
    // lets it through: without this mode, a wrong field looks like behavior and is
    // just decoration. The field list does NOT live here — it lives in
    // .claude/schemas/extensions.json, so that adding a field doesn't require
    // touching Java. Rationale and design:
    // .claude/decisions/0001-schema-frontmatter-extensions.md

    static final String SCHEMA_FILE = ".claude/schemas/extensions.json";

    static void schema(String stdin) throws Exception {
        // If the Stop hook already blocked before, don't block again: avoids cycles.
        if (Pattern.compile("\"stop_hook_active\"\\s*:\\s*true").matcher(stdin).find()) return;

        Map<String, Object> sch = asMap(Json.parse(readOrNull(ROOT.resolve(SCHEMA_FILE))));
        if (sch == null) {
            err("⚠️  " + SCHEMA_FILE + " missing or invalid.");
            err("   Frontmatter validation OFF — nothing was checked.");
            return;
        }

        Map<String, Object> in = asMap(get(Json.parse(stdin), "tool_input"));
        String file = in != null ? asStr(in.get("file_path")) : filePath(stdin);

        List<String> errors = new ArrayList<>();
        if (file == null) {
            sweep(sch, errors);                       // Stop, or manual invocation
        } else {
            String rel = relative(Paths.get(file));
            // Write brings the whole file in tool_input.content and is validated before
            // writing. Edit brings old_string/new_string — there only disk works.
            String content = in != null ? asStr(in.get("content")) : null;
            if (content == null) content = readOrNull(Paths.get(file));
            if (content == null) return;              // file deleted or unreadable
            checkOne(sch, rel, content, errors);
        }

        if (!errors.isEmpty()) {
            err("❌ Invalid frontmatter — " + errors.size()
                    + (errors.size() == 1 ? " problem" : " problems"));
            errors.forEach(ArchHook::err);
            err("");
            err("Valid fields by type: " + SCHEMA_FILE);
            err("What each field is for: .claude/skills/claude-code-architect-designer"
                    + "/references/frontmatter-fields.md");
            System.exit(2);
        }
    }

    /** Sweeps every file that some schema `match` captures. */
    static void sweep(Map<String, Object> sch, List<String> errors) throws IOException {
        List<String> globs = new ArrayList<>();
        Map<String, Object> types = asMap(sch.get("types"));
        if (types != null) {
            for (Object t : types.values()) {
                String g = asStr(asMap(t) == null ? null : asMap(t).get("match"));
                if (g != null) globs.add(g);
            }
        }
        String sg = asStr(get(sch, "settings", "match"));
        if (sg != null) globs.add(sg);
        globs.addAll(asStrList(get(sch, "mcp", "match")));

        for (String g : globs) {
            Path base = ROOT.resolve(g.substring(0, Math.max(0, g.indexOf('*'))))
                    .normalize();
            if (!Files.isDirectory(base)) {
                if (Files.isRegularFile(base)) {       // glob without `*`: settings.json
                    checkOne(sch, relative(base), readOrNull(base), errors);
                }
                continue;
            }
            Pattern re = glob(g);
            try (Stream<Path> walk = Files.walk(base)) {
                List<Path> hits = walk.filter(Files::isRegularFile)
                        .filter(f -> re.matcher(relative(f)).matches())
                        .sorted().collect(Collectors.toList());
                for (Path f : hits) checkOne(sch, relative(f), readOrNull(f), errors);
            }
        }
    }

    /** Validates one file. A path that no `match` captures exits silently. */
    static void checkOne(Map<String, Object> sch, String rel, String content,
                         List<String> errors) {
        if (content == null) return;

        if (matches(asStr(get(sch, "settings", "match")), rel)) {
            checkSettings(sch, rel, content, errors);
            return;
        }

        if (matchesAny(asStrList(get(sch, "mcp", "match")), rel)) {
            checkMcp(asMap(sch.get("mcp")), rel, content, errors);
            return;
        }

        Map<String, Object> types = asMap(sch.get("types"));
        if (types == null) return;
        for (Map.Entry<String, Object> e : types.entrySet()) {
            Map<String, Object> t = asMap(e.getValue());
            if (t == null || !matches(asStr(t.get("match")), rel)) continue;
            checkFrontmatter(sch, e.getKey(), t, rel, content, errors);
            return;
        }
    }

    static void checkFrontmatter(Map<String, Object> sch, String type,
                                 Map<String, Object> t, String rel, String content,
                                 List<String> errors) {
        Map<String, String> fm = frontmatter(content);
        if (fm == null) {
            errors.add("  " + rel + " — no frontmatter block closed by `---`"
                    + " (type '" + type + "')");
            return;
        }

        for (String req : asStrList(t.get("required"))) {
            if (!fm.containsKey(req)) {
                errors.add("  " + rel + " — missing required field `" + req + "`");
            }
        }

        List<String> allowed = asStrList(t.get("allowed"));
        List<String> forbidden = asStrList(sch.get("forbidden_everywhere"));
        for (String key : fm.keySet()) {
            if (forbidden.contains(key)) {
                errors.add("  " + rel + " — `" + key + "` is not a native field."
                        + " What it used to carry lives in the `## Contrato` section of the body");
                continue;
            }
            if (allowed.contains(key)) continue;
            String hint = nearest(key, allowed);
            errors.add("  " + rel + " — `" + key + "` is not a field of '" + type + "'"
                    + (hint != null
                        ? ". It is written `" + hint + "` (skills use kebab-case,"
                          + " agents use camelCase)"
                        : ". The runtime silently ignores it"));
        }

        Map<String, Object> enums = asMap(t.get("enum"));
        if (enums == null) return;
        for (Map.Entry<String, Object> e : enums.entrySet()) {
            String v = fm.get(e.getKey());
            List<String> ok = asStrList(e.getValue());
            if (v == null || v.isEmpty() || ok.contains(v)) continue;
            errors.add("  " + rel + " — `" + e.getKey() + ": " + v + "` invalid."
                    + " Values: " + String.join(", ", ok));
        }
    }

    /** Validates the top-level keys and each hook entry of settings.json. */
    static void checkSettings(Map<String, Object> sch, String rel, String content,
                              List<String> errors) {
        Map<String, Object> root = asMap(Json.parse(content));
        if (root == null) { errors.add("  " + rel + " — invalid JSON"); return; }

        List<String> topAllowed = asStrList(get(sch, "settings", "allowed"));
        if (!topAllowed.isEmpty()) {
            for (String key : root.keySet()) {
                if (!topAllowed.contains(key)) {
                    errors.add("  " + rel + " — `" + key + "` is not a recognized top-level key");
                }
            }
        }

        Map<String, Object> hooks = asMap(root.get("hooks"));
        if (hooks == null) return;

        List<String> req = asStrList(get(sch, "settings", "hook_entry", "required"));
        List<String> allowed = asStrList(get(sch, "settings", "hook_entry", "allowed"));

        for (Map.Entry<String, Object> ev : hooks.entrySet()) {
            for (Object group : asList(ev.getValue())) {
                Map<String, Object> g = asMap(group);
                if (g == null) continue;
                for (Object entry : asList(g.get("hooks"))) {
                    Map<String, Object> h = asMap(entry);
                    if (h == null) continue;
                    String where = rel + " › " + ev.getKey();
                    for (String r : req) {
                        if (!h.containsKey(r)) {
                            errors.add("  " + where + " — hook entry missing `" + r + "`");
                        }
                    }
                    for (String k : h.keySet()) {
                        if (!allowed.contains(k)) {
                            errors.add("  " + where + " — `" + k
                                    + "` is not a hook entry field");
                        }
                    }
                }
            }
        }
    }

    /**
     * Validates .mcp.json (and its project-bootstrap template): unknown top-level or
     * per-server fields, missing field the declared transport requires, a reserved or
     * malformed server name, and a literal secret in `headers`/`env` — invariant 11,
     * @CLAUDE.md. The field list lives in extensions.json's `mcp` block, same
     * single-owner discipline as the frontmatter tables above.
     */
    static void checkMcp(Map<String, Object> mcpSchema, String rel, String content,
                        List<String> errors) {
        if (mcpSchema == null) return;

        Map<String, Object> root = asMap(Json.parse(content));
        if (root == null) { errors.add("  " + rel + " — invalid JSON"); return; }

        List<String> rootAllowed = asStrList(mcpSchema.get("root_allowed"));
        for (String key : root.keySet()) {
            if (!rootAllowed.contains(key)) {
                errors.add("  " + rel + " — `" + key
                        + "` is not a valid top-level key. Only `mcpServers`");
            }
        }

        Map<String, Object> servers = asMap(root.get("mcpServers"));
        if (servers == null) return;

        List<String> serverAllowed = asStrList(mcpSchema.get("server_allowed"));
        Map<String, Object> requiredByType = asMap(mcpSchema.get("required_by_type"));
        String namePattern = asStr(mcpSchema.get("name_pattern"));
        Pattern nameRe = namePattern == null ? null : Pattern.compile(namePattern);
        List<String> reserved = asStrList(mcpSchema.get("reserved_names"));
        Map<String, Object> secretScan = asMap(mcpSchema.get("secret_scan"));
        List<String> secretFields = secretScan == null ? List.of() : asStrList(secretScan.get("fields"));
        Pattern keyRe = secretScan == null || asStr(secretScan.get("key_pattern")) == null
                ? null : Pattern.compile(asStr(secretScan.get("key_pattern")));
        List<String> valuePrefixes = secretScan == null
                ? List.of() : asStrList(secretScan.get("value_prefixes"));

        for (Map.Entry<String, Object> e : servers.entrySet()) {
            String name = e.getKey();
            Map<String, Object> server = asMap(e.getValue());
            if (server == null) {
                errors.add("  " + rel + " — server `" + name + "` is not an object");
                continue;
            }
            if (reserved.contains(name)) {
                errors.add("  " + rel + " — server name `" + name
                        + "` is reserved by the runtime");
            }
            if (nameRe != null && !nameRe.matcher(name).matches()) {
                errors.add("  " + rel + " — server name `" + name
                        + "` doesn't match `" + namePattern + "`");
            }
            for (String key : server.keySet()) {
                if (!serverAllowed.contains(key)) {
                    errors.add("  " + rel + " — server `" + name
                            + "` has unknown field `" + key + "`");
                }
            }

            String type = asStr(server.get("type"));
            if (type == null) {
                errors.add("  " + rel + " — server `" + name + "` is missing `type`");
            } else if (requiredByType != null && !requiredByType.containsKey(type)) {
                errors.add("  " + rel + " — server `" + name + "` has unknown `type: "
                        + type + "`. Allowed: " + String.join(", ", requiredByType.keySet()));
            } else if (requiredByType != null) {
                for (String req : asStrList(requiredByType.get(type))) {
                    if (!server.containsKey(req)) {
                        errors.add("  " + rel + " — server `" + name + "` (type `" + type
                                + "`) is missing required field `" + req + "`");
                    }
                }
            }

            for (String field : secretFields) {
                Map<String, Object> block = asMap(server.get(field));
                if (block == null) continue;
                for (Map.Entry<String, Object> kv : block.entrySet()) {
                    String value = asStr(kv.getValue());
                    if (value != null && looksLikeSecret(kv.getKey(), value, keyRe, valuePrefixes)) {
                        errors.add("  " + rel + " — server `" + name + "` field `" + field
                                + "." + kv.getKey() + "` looks like a literal secret."
                                + " Use `${VAR}` / `${VAR:-default}`, `oauth`, or"
                                + " `headersHelper` instead — invariant 11, @CLAUDE.md");
                    }
                }
            }
        }
    }

    /**
     * A value with no `${...}` expansion whose key name looks credential-shaped, or
     * whose value starts with a known token prefix, is a literal secret. Any `${`
     * anywhere in the value is treated as safe — "Bearer ${API_TOKEN}" is the
     * documented good pattern and must not be flagged alongside "Bearer abc123xyz".
     */
    static boolean looksLikeSecret(String key, String value, Pattern keyRe,
                                   List<String> valuePrefixes) {
        if (value.contains("${")) return false;
        boolean keySensitive = keyRe != null && keyRe.matcher(key).find();
        boolean valueSensitive = valuePrefixes.stream().anyMatch(value::startsWith);
        return keySensitive || valueSensitive;
    }

    static boolean matchesAny(List<String> globPatterns, String rel) {
        for (String g : globPatterns) if (matches(g, rel)) return true;
        return false;
    }

    /**
     * Top-level frontmatter keys and their scalar value, in file order. Returns
     * null when there is no closed `---` block. No YAML library: only unindented
     * keys matter. `#` comments are ignored — two rules in this repo use them
     * inside frontmatter.
     */
    static Map<String, String> frontmatter(String content) {
        List<String> lines = content.lines().collect(Collectors.toList());
        int start = -1;
        for (int i = 0; i < lines.size(); i++) {
            String l = lines.get(i).strip();
            if (l.isEmpty()) continue;
            if (l.equals("---")) start = i;
            break;
        }
        if (start < 0) return null;

        Map<String, String> fm = new LinkedHashMap<>();
        for (int i = start + 1; i < lines.size(); i++) {
            String raw = lines.get(i);
            if (raw.strip().equals("---")) return fm;
            if (raw.isBlank() || raw.stripLeading().startsWith("#")) continue;
            if (Character.isWhitespace(raw.charAt(0)) || raw.startsWith("-")) continue;
            int c = raw.indexOf(':');
            if (c <= 0) continue;
            String v = raw.substring(c + 1).strip();
            if (v.startsWith(">") || v.startsWith("|")) v = "";   // block scalar
            fm.put(raw.substring(0, c).strip(), v);
        }
        return null;                                  // block opened and never closed
    }

    /** The allowed field that only differs in naming convention, or null. */
    static String nearest(String key, List<String> allowed) {
        String n = key.toLowerCase(Locale.ROOT).replace("-", "").replace("_", "");
        for (String a : allowed) {
            if (a.toLowerCase(Locale.ROOT).replace("-", "").replace("_", "").equals(n)) {
                return a;
            }
        }
        return null;
    }

    static boolean matches(String globPattern, String rel) {
        return globPattern != null && glob(globPattern).matcher(rel).matches();
    }

    /** Glob to regex: `**` crosses `/`, `*` does not. */
    static Pattern glob(String g) {
        StringBuilder b = new StringBuilder("^");
        for (int i = 0; i < g.length(); i++) {
            char c = g.charAt(i);
            if (c == '*') {
                if (i + 1 < g.length() && g.charAt(i + 1) == '*') { b.append(".*"); i++; }
                else b.append("[^/]*");
            } else if (c == '?') {
                b.append("[^/]");
            } else {
                b.append(Pattern.quote(String.valueOf(c)));
            }
        }
        return Pattern.compile(b.append("$").toString());
    }

    static String readOrNull(Path p) {
        try { return Files.isRegularFile(p)
                ? Files.readString(p, StandardCharsets.UTF_8) : null; }
        catch (IOException e) { return null; }
    }

    // ── audit ────────────────────────────────────────────────────────────────
    //
    // Execution trail of the project's orchestrator skills — the ones carrying
    // `disable-model-invocation: true`. It is a hook and not a skill because the record
    // has to survive the model forgetting, the session dying, and the user pressing
    // Ctrl+C. A skill can promise that; only a lifecycle event delivers it.
    //
    // Phases (args[1]), one per hook event:
    //   prompt    UserPromptSubmit               opens a run when the prompt is `/<orchestrator>`
    //   call      PreToolUse Skill|Task          one node of the chain
    //   file      PostToolUse Write|Edit         file touched — feeds rule inference by glob
    //   fail      PostToolUseFailure             rework counter
    //   stopfail  StopFailure                    the turn ended in error
    //   perm      PermissionRequest|Denied       permission asked for mid-run
    //   agent     SubagentStop                   closes the current agent node
    //   compact   PreCompact                     the context overflowed
    //   flush     Stop                           rewrites the report
    //   close     SessionEnd                     stamps the final status and closes the run
    //
    // Every phase appends one line to .claude/audit-usage/.state/<session>.ndjson, and
    // the report is DERIVED from that log at flush time. Append-only survives a kill -9;
    // a read-modify-write of a structured file does not.
    //
    // Switched off by the absence of .claude/audit-usage/: every phase returns
    // immediately. That is why this meta-repository, which does not create the
    // directory, pays nothing for a mode wired only into the generated project.

    static final String AUDIT_DIR = ".claude/audit-usage";
    static final Locale PT = Locale.forLanguageTag("pt-BR");

    static void audit(String phase, String stdin) throws Exception {
        Path dir = ROOT.resolve(AUDIT_DIR);
        if (!Files.isDirectory(dir)) return;

        Object in = Json.parse(stdin);
        String session = asStr(get(in, "session_id"));
        if (session == null || session.isBlank()) session = "unknown";
        Path log = dir.resolve(".state").resolve(session.replaceAll("[^A-Za-z0-9_-]", "_") + ".ndjson");

        switch (phase) {
            case "prompt"   -> auditPrompt(dir, log, in);
            case "call"     -> auditCall(log, in);
            case "file"     -> auditFile(log, in);
            case "fail"     -> append(log, ev("fail", "tool", asStr(get(in, "tool_name"))));
            case "stopfail" -> append(log, ev("stop_fail"));
            case "perm"     -> append(log, ev("perm",
                                       "tool", asStr(get(in, "tool_name")),
                                       "event", asStr(get(in, "hook_event_name"))));
            case "agent"    -> append(log, ev("agent_end"));
            case "compact"  -> append(log, ev("compact"));
            case "flush"    -> auditRender(dir, log, in, false);
            case "close"    -> auditRender(dir, log, in, true);
            default         -> { }
        }
    }

    /**
     * Opens a run when the prompt invokes an orchestrator. Which skills qualify is data,
     * not code: any `.claude/skills/<name>/SKILL.md` carrying
     * `disable-model-invocation: true` counts, so a skill written later is audited
     * without this file being touched — @CLAUDE.md invariant 7.
     */
    static void auditPrompt(Path dir, Path log, Object in) throws Exception {
        String prompt = asStr(get(in, "prompt"));
        if (prompt == null) return;
        Matcher m = Pattern.compile("^\\s*/([a-z0-9][a-z0-9-]*)(.*)$", Pattern.DOTALL)
                .matcher(prompt);
        if (!m.find() || !isOrchestrator(m.group(1))) return;

        // A second `/command` in the same session ends the run in progress: the report
        // of what already ran is worth more than a run left open forever.
        if (Files.isRegularFile(log)) auditRender(dir, log, in, true);

        Files.createDirectories(log.getParent());
        Files.writeString(log, "", StandardCharsets.UTF_8);

        String stripped = prompt.strip();
        String redacted = redact(stripped);
        // `args` is redacted too, not just `prompt`: it is a slice of the same text and
        // it is what the report puts in the title. Redacting one and not the other
        // leaks the secret in the most visible line of the file.
        append(log, ev("run_start",
                "skill", m.group(1),
                "args", redact(m.group(2).strip()),
                "prompt", redacted,
                "prompt_sha256", sha256(prompt),
                "redacted", String.valueOf(!redacted.equals(stripped)),
                "head", gitShort(),
                "perm_before", String.join(" ", localPermissions())));
    }

    static boolean isOrchestrator(String skill) {
        String content = readOrNull(ROOT.resolve(".claude/skills").resolve(skill).resolve("SKILL.md"));
        if (content == null) return false;
        Map<String, String> fm = frontmatter(content);
        return fm != null && "true".equals(fm.get("disable-model-invocation"));
    }

    static void auditCall(Path log, Object in) {
        Map<String, Object> ti = asMap(get(in, "tool_input"));
        if (ti == null) return;
        String tool = asStr(get(in, "tool_name"));
        if ("Skill".equals(tool)) {
            append(log, ev("skill", "name", asStr(ti.get("skill")), "args", asStr(ti.get("args"))));
        } else if ("Task".equals(tool) || "Agent".equals(tool)) {
            append(log, ev("agent",
                    "name", asStr(ti.get("subagent_type")),
                    "detail", asStr(ti.get("description")),
                    "model", asStr(ti.get("model"))));
        }
    }

    static void auditFile(Path log, Object in) {
        String f = asStr(get(in, "tool_input", "file_path"));
        if (f == null) return;
        append(log, ev("file", "op", asStr(get(in, "tool_name")),
                "path", relative(Paths.get(f))));
    }

    /** One NDJSON event. A null value is dropped instead of written as "null". */
    static String ev(String name, String... kv) {
        StringBuilder b = new StringBuilder("{\"t\":").append(System.currentTimeMillis())
                .append(",\"iso\":\"").append(Instant.now()).append('"')
                .append(",\"e\":\"").append(name).append('"');
        for (int i = 0; i + 1 < kv.length; i += 2) {
            if (kv[i + 1] == null) continue;
            b.append(",\"").append(kv[i]).append("\":\"")
             .append(jsonEscape(kv[i + 1])).append('"');
        }
        return b.append('}').toString();
    }

    static String jsonEscape(String s) {
        StringBuilder b = new StringBuilder();
        for (char c : s.toCharArray()) {
            switch (c) {
                case '"'  -> b.append("\\\"");
                case '\\' -> b.append("\\\\");
                case '\n' -> b.append("\\n");
                case '\r' -> b.append("\\r");
                case '\t' -> b.append("\\t");
                default   -> {
                    if (c < 0x20) b.append(String.format(Locale.ROOT, "\\u%04x", (int) c));
                    else b.append(c);
                }
            }
        }
        return b.toString();
    }

    /** Appends to an open run. No open run, no record — that is the off switch. */
    static void append(Path log, String line) {
        if (!Files.isRegularFile(log)) return;
        try {
            Files.writeString(log, line + "\n", StandardCharsets.UTF_8,
                    StandardOpenOption.CREATE, StandardOpenOption.APPEND);
        } catch (IOException ignored) { }
    }

    /**
     * Blanks anything credential-shaped before the prompt reaches a versioned file.
     * The patterns live in extensions.json's `audit.redact` block, never here — same
     * single-owner discipline as every other list this hook reads (invariant 10). A
     * secret pasted into a prompt and committed is irreversible; invariant 11 exists
     * for exactly this, and `.claude/audit-usage/` is versioned on purpose.
     */
    static String redact(String text) {
        Map<String, Object> r = asMap(get(Json.parse(readOrNull(ROOT.resolve(SCHEMA_FILE))),
                "audit", "redact"));
        if (r == null) return text;
        String out = text;
        for (String p : asStrList(r.get("patterns"))) {
            try { out = Pattern.compile(p).matcher(out).replaceAll("$1[REDACTED]"); }
            catch (Exception ignored) { }
        }
        for (String prefix : asStrList(r.get("value_prefixes"))) {
            out = Pattern.compile(Pattern.quote(prefix) + "\\S+").matcher(out)
                    .replaceAll(Matcher.quoteReplacement(prefix + "[REDACTED]"));
        }
        return out;
    }

    static String sha256(String s) {
        try {
            byte[] d = java.security.MessageDigest.getInstance("SHA-256")
                    .digest(s.getBytes(StandardCharsets.UTF_8));
            StringBuilder b = new StringBuilder();
            for (byte x : d) b.append(String.format(Locale.ROOT, "%02x", x));
            return b.substring(0, 16);
        } catch (Exception e) { return "?"; }
    }

    static String gitShort() {
        try {
            Proc p = run(gitCmd(), "rev-parse", "--short", "HEAD");
            return p.exit == 0 && !p.out.isEmpty() ? p.out.get(0).strip() : null;
        } catch (Exception e) { return null; }
    }

    /**
     * `permissions.*` of settings.local.json — where a rule granted mid-session lands.
     * Diffing this file before and after is the only observation of "permission added"
     * that does not depend on an undocumented hook payload.
     */
    static List<String> localPermissions() {
        Map<String, Object> p = asMap(get(Json.parse(
                readOrNull(ROOT.resolve(".claude/settings.local.json"))), "permissions"));
        if (p == null) return List.of();
        List<String> out = new ArrayList<>();
        for (String k : List.of("allow", "ask", "deny")) {
            for (String v : asStrList(p.get(k))) out.add(k + ": " + v);
        }
        return out;
    }

    record Node(String kind, String name, String detail, long start, int depth) {}

    record Tokens(long in, long out, long cacheRead, long cacheWrite, String model) {
        long billable() { return in + out + cacheWrite; }
        long contextRead() { return in + cacheRead; }
    }

    /**
     * Rewrites the report from the event log, from scratch, every time. Idempotent by
     * construction: an execution killed halfway keeps the last flush, marked
     * "em andamento", instead of leaving nothing behind.
     */
    static void auditRender(Path dir, Path log, Object in, boolean closing) throws Exception {
        if (!Files.isRegularFile(log)) return;
        List<Map<String, Object>> events = new ArrayList<>();
        for (String line : Files.readAllLines(log, StandardCharsets.UTF_8)) {
            Map<String, Object> e = asMap(Json.parse(line));
            if (e != null && asStr(e.get("e")) != null) events.add(e);
        }
        if (events.isEmpty()) return;
        Map<String, Object> s0 = events.get(0);
        if (!"run_start".equals(asStr(s0.get("e")))) return;

        String skill    = orDash(asStr(s0.get("skill")));
        String args     = asStr(s0.get("args"));
        String startIso = asStr(s0.get("iso"));
        long   startMs  = num(s0.get("t"));
        long   lastMs   = num(events.get(events.size() - 1).get("t"));
        final long endMs = lastMs > startMs ? lastMs : System.currentTimeMillis();
        long   total    = Math.max(1, endMs - startMs);

        List<Node> nodes = new ArrayList<>();
        Set<String> touched = new LinkedHashSet<>();
        Map<String, Integer> fails = new LinkedHashMap<>();
        Map<String, Integer> ops = new LinkedHashMap<>();
        List<String> perms = new ArrayList<>();
        int compacts = 0;
        boolean errored = false;
        int depth = 1;

        for (Map<String, Object> e : events) {
            String kind = asStr(e.get("e"));
            switch (kind) {
                case "skill" -> nodes.add(new Node("skill", orDash(asStr(e.get("name"))),
                        asStr(e.get("args")), num(e.get("t")), depth));
                case "agent" -> {
                    nodes.add(new Node("agent", orDash(asStr(e.get("name"))),
                            asStr(e.get("model")), num(e.get("t")), depth));
                    depth++;
                }
                case "agent_end" -> depth = Math.max(1, depth - 1);
                case "file" -> {
                    String path = asStr(e.get("path"));
                    if (path != null) touched.add(path);
                    ops.merge(orDash(asStr(e.get("op"))), 1, Integer::sum);
                }
                case "fail" -> fails.merge(orDash(asStr(e.get("tool"))), 1, Integer::sum);
                case "stop_fail" -> errored = true;
                case "compact" -> compacts++;
                case "perm" -> perms.add(orDash(asStr(e.get("tool"))));
                default -> { }
            }
        }

        Tokens tk = auditTokens(asStr(get(in, "transcript_path")), startIso);
        List<String> added = new ArrayList<>(localPermissions());
        added.removeAll(Arrays.asList(orEmpty(asStr(s0.get("perm_before"))).split(" ")));
        String headStart = asStr(s0.get("head"));
        String headEnd   = gitShort();

        String status = !closing ? "⏳ em andamento"
                : errored ? "❌ erro"
                : fails.isEmpty() ? "✅ sucesso"
                : "⚠️ sucesso com falhas recuperadas";

        StringBuilder md = new StringBuilder();
        md.append("# 🧾 Auditoria de execução — `/").append(skill)
          .append(args == null || args.isBlank() ? "" : " " + args).append("`\n\n");

        md.append("| | |\n|---|---|\n")
          .append("| 🎯 Skill | `/").append(skill).append("` |\n")
          .append("| 🕐 Início | ").append(startIso).append(" |\n")
          .append("| 🏁 Fim | ").append(Instant.ofEpochMilli(endMs)).append(" |\n")
          .append("| ⏱️ Duração | ").append(hms(total)).append(" |\n")
          .append("| ").append(status.substring(0, status.indexOf(' ')))
          .append(" Status | ").append(status.substring(status.indexOf(' ') + 1)).append(" |\n")
          .append("| 🤖 Modelo | ").append(orDash(tk.model())).append(" |\n")
          .append("| 🌿 HEAD | ").append(orDash(headStart)).append(" → ")
          .append(orDash(headEnd)).append(" |\n\n");

        md.append("## 📜 Comando inicial\n\n```text\n")
          .append(orEmpty(asStr(s0.get("prompt")))).append("\n```\n\n")
          .append("`sha256` do texto original (antes da redação): `")
          .append(orDash(asStr(s0.get("prompt_sha256")))).append("` · segredos removidos: ")
          .append("true".equals(asStr(s0.get("redacted"))) ? "**sim**" : "não").append("\n\n");

        List<Node> ranked = new ArrayList<>(nodes);
        ranked.sort((a, b) -> Long.compare(dur(b, nodes, endMs), dur(a, nodes, endMs)));
        if (!ranked.isEmpty()) {
            md.append("## 🏆 Etapas mais caras\n\n| # | Etapa | Duração | % |\n|---|---|---|---|\n");
            for (int i = 0; i < Math.min(3, ranked.size()); i++) {
                Node n = ranked.get(i);
                long d = dur(n, nodes, endMs);
                md.append("| ").append(i + 1).append(" | `").append(n.name()).append("` | ")
                  .append(hms(d)).append(" | ").append(pct(d, total)).append(" |\n");
            }
            md.append('\n');
        }

        md.append("## 🔗 Encadeamento\n\n```text\n");
        md.append(pad("/" + skill, 46)).append(bar(1.0)).append(' ')
          .append(pad(hms(total), 9)).append("100%\n");
        for (int i = 0; i < nodes.size(); i++) {
            Node n = nodes.get(i);
            long d = dur(n, nodes, endMs);
            boolean last = i == nodes.size() - 1;
            String label = "  ".repeat(Math.max(0, n.depth() - 1)) + (last ? "└─ " : "├─ ")
                    + ("agent".equals(n.kind()) ? "🤖 " : "📘 ") + n.name()
                    + (n.detail() == null || n.detail().isBlank() ? "" : " (" + n.detail() + ")");
            md.append(pad(label, 46)).append(bar((double) d / total)).append(' ')
              .append(pad(hms(d), 9)).append(pct(d, total)).append('\n');
        }
        md.append("```\n\n")
          .append("> Duração de um nó = do seu início até o próximo nó de mesma profundidade")
          .append(" ou menor. É atribuição por janela, não medição isolada.\n\n");

        md.append("## 📊 Tokens (agregado)\n\n")
          .append("| Métrica | Valor |\n|---|---|\n")
          .append("| ⬇️ input | ").append(n(tk.in())).append(" |\n")
          .append("| ⬆️ output | ").append(n(tk.out())).append(" |\n")
          .append("| ♻️ cache read | ").append(n(tk.cacheRead())).append(" |\n")
          .append("| 💾 cache write | ").append(n(tk.cacheWrite())).append(" |\n")
          .append("| 🧮 faturável (input + output + cache write) | **").append(n(tk.billable())).append("** |\n");
        String cost = auditCost(tk);
        md.append("| 💰 custo estimado | ")
          .append(cost == null ? "— (preencha `" + AUDIT_DIR + "/pricing.json`)" : "**" + cost + "**")
          .append(" |\n\n");
        long ctx = tk.contextRead();
        double hit = ctx == 0 ? 0 : (double) tk.cacheRead() / ctx;
        md.append("Cache hit ").append(pct(tk.cacheRead(), Math.max(1, ctx))).append(" ")
          .append(bar(hit)).append("\n\n");

        md.append("## 🔐 Permissões adicionadas durante a execução\n\n");
        if (added.isEmpty()) {
            md.append("Nenhuma. `settings.local.json` não mudou entre o início e o fim.\n\n");
        } else {
            md.append("| Regra |\n|---|\n");
            for (String a : added) md.append("| `").append(a).append("` |\n");
            md.append('\n');
        }
        if (!perms.isEmpty()) {
            md.append("Solicitações observadas (").append(perms.size()).append("): ")
              .append(String.join(", ", new LinkedHashSet<>(perms))).append("\n\n");
        }

        md.append("## 📐 Regras carregadas (inferidas por território)\n\n");
        Map<String, List<String>> rules = auditRules(touched);
        if (rules.isEmpty()) {
            md.append("Nenhum arquivo tocado casa com o `paths` de alguma regra.\n\n");
        } else {
            md.append("| Regra | Glob | Arquivos |\n|---|---|---|\n");
            for (Map.Entry<String, List<String>> e : rules.entrySet()) {
                String[] parts = e.getKey().split(" ", 2);
                md.append("| `").append(parts[0]).append("` | `").append(parts[1])
                  .append("` | ").append(e.getValue().size()).append(" |\n");
            }
            md.append("\n> Inferência, não observação: nenhum evento de hook expõe qual regra")
              .append(" entrou em contexto. Isto é \"as regras que **deveriam** ter carregado\".\n\n");
        }

        md.append("## 📁 Arquivos tocados\n\n");
        if (touched.isEmpty()) {
            md.append("Nenhum.\n\n");
        } else {
            md.append(ops.entrySet().stream().map(e -> e.getValue() + "× " + e.getKey())
                    .collect(Collectors.joining(" · ")))
              .append(" — ").append(touched.size())
              .append(touched.size() == 1 ? " arquivo distinto" : " arquivos distintos")
              .append("\n\n```text\n")
              .append(String.join("\n", touched)).append("\n```\n\n");
        }

        md.append("## 🔁 Retrabalho\n\n");
        if (fails.isEmpty()) {
            md.append("Nenhuma ferramenta falhou. 🎉\n\n");
        } else {
            md.append("| Ferramenta | Falhas |\n|---|---|\n");
            for (Map.Entry<String, Integer> e : fails.entrySet()) {
                md.append("| `").append(e.getKey()).append("` | ").append(e.getValue()).append(" |\n");
            }
            md.append("\n> Falha repetida na mesma ferramenta é sinal de spec ruim, não de azar.\n\n");
        }

        if (compacts > 0) {
            md.append("## ⚠️ Incidentes\n\n🗜️ Contexto compactado ").append(compacts)
              .append("× durante a execução — qualidade da saída cai depois de cada compactação.\n\n");
        }

        if (headStart != null && headEnd != null && !headStart.equals(headEnd)) {
            md.append("## 🌿 Commits da execução\n\n```text\n")
              .append(String.join("\n", gitLog(headStart, headEnd))).append("\n```\n\n");
        }

        md.append("---\n\n*Gerado por `ArchHook.java audit` · `")
          .append(AUDIT_DIR).append("/`*\n");

        String stamp = orEmpty(startIso).replace(':', '-');
        int dot = stamp.indexOf('.');
        if (dot > 0) stamp = stamp.substring(0, dot);
        Path report = dir.resolve(stamp + "--" + skill + ".md");
        Files.writeString(report, md.toString(), StandardCharsets.UTF_8);

        if (closing) {
            Files.writeString(dir.resolve("history.jsonl"),
                    ev("run", "skill", skill, "start", startIso,
                       "duration_ms", String.valueOf(total),
                       "status", status,
                       "tokens_billable", String.valueOf(tk.billable()),
                       "cost", cost,
                       "files", String.valueOf(touched.size()),
                       "failures", String.valueOf(fails.values().stream().mapToInt(Integer::intValue).sum()),
                       "report", relative(report)) + "\n",
                    StandardCharsets.UTF_8, StandardOpenOption.CREATE, StandardOpenOption.APPEND);
            Files.deleteIfExists(log);
        }
    }

    /** From this node's start to the next node at the same depth or shallower. */
    static long dur(Node n, List<Node> all, long endMs) {
        for (Node o : all) {
            if (o.start() > n.start() && o.depth() <= n.depth()) return Math.max(0, o.start() - n.start());
        }
        return Math.max(0, endMs - n.start());
    }

    /**
     * Token totals from the session transcript — the only place the runtime writes real
     * `usage`. Timestamps are ISO-8601 in UTC, so a lexicographic comparison against the
     * run's start is enough and avoids parsing dates.
     */
    static Tokens auditTokens(String transcript, String sinceIso) {
        long i = 0, o = 0, cr = 0, cw = 0;
        String model = null;
        if (transcript == null) return new Tokens(0, 0, 0, 0, null);
        Path p = Paths.get(transcript);
        if (!Files.isRegularFile(p)) return new Tokens(0, 0, 0, 0, null);
        try (BufferedReader r = Files.newBufferedReader(p, StandardCharsets.UTF_8)) {
            String line;
            while ((line = r.readLine()) != null) {
                Object e = Json.parse(line);
                String ts = asStr(get(e, "timestamp"));
                if (ts != null && sinceIso != null && ts.compareTo(sinceIso) < 0) continue;
                Map<String, Object> u = asMap(get(e, "message", "usage"));
                if (u == null) continue;
                i  += num(u.get("input_tokens"));
                o  += num(u.get("output_tokens"));
                cr += num(u.get("cache_read_input_tokens"));
                cw += num(u.get("cache_creation_input_tokens"));
                String m = asStr(get(e, "message", "model"));
                if (m != null) model = m;
            }
        } catch (IOException ignored) { }
        return new Tokens(i, o, cr, cw, model);
    }

    /**
     * Prices are data, never memory — the same discipline invariant 8 imposes on Java
     * and Spring versions. pricing.json ships with null values on purpose: an unfilled
     * price prints as "não configurado", never as a confident US$ 0.00.
     */
    static String auditCost(Tokens t) {
        Map<String, Object> pr = asMap(Json.parse(readOrNull(ROOT.resolve(AUDIT_DIR + "/pricing.json"))));
        if (pr == null || t.model() == null) return null;
        Map<String, Object> m = asMap(get(pr, "models", t.model()));
        if (m == null) return null;
        Double in = dbl(m.get("input")), out = dbl(m.get("output")),
               cr = dbl(m.get("cache_read")), cw = dbl(m.get("cache_write"));
        if (in == null || out == null || cr == null || cw == null) return null;
        Double per = dbl(pr.get("per"));
        double unit = per == null || per == 0 ? 1_000_000d : per;
        double usd = (t.in() * in + t.out() * out + t.cacheRead() * cr + t.cacheWrite() * cw) / unit;
        String cur = asStr(pr.get("currency"));
        return String.format(PT, "%s %.2f", cur == null ? "USD" : cur, usd);
    }

    /** Rules whose `paths` capture at least one file touched during the run. */
    static Map<String, List<String>> auditRules(Set<String> touched) throws IOException {
        Map<String, List<String>> hit = new LinkedHashMap<>();
        Path rules = ROOT.resolve(".claude/rules");
        if (!Files.isDirectory(rules) || touched.isEmpty()) return hit;
        try (Stream<Path> s = Files.list(rules)) {
            List<Path> files = s.filter(f -> f.toString().endsWith(".md")).sorted()
                    .collect(Collectors.toList());
            for (Path f : files) {
                for (String g : ruleGlobs(f)) {
                    Pattern re = glob(g);
                    List<String> matched = touched.stream()
                            .filter(t -> re.matcher(t).matches()).sorted()
                            .collect(Collectors.toList());
                    if (!matched.isEmpty()) {
                        hit.put(f.getFileName() + " " + g, matched);
                    }
                }
            }
        }
        return hit;
    }

    /**
     * The `paths` of a rule. `frontmatter()` reads unindented scalars only, and this
     * repo writes `paths` as an indented block list — so the block is read here.
     */
    static List<String> ruleGlobs(Path file) {
        String c = readOrNull(file);
        if (c == null) return List.of();
        List<String> out = new ArrayList<>();
        boolean inside = false;
        for (String raw : c.lines().collect(Collectors.toList())) {
            String l = raw.strip();
            if (raw.startsWith("paths:")) { inside = true; continue; }
            if (!inside) continue;
            if (l.startsWith("#")) continue;
            if (!l.startsWith("- ")) break;
            out.add(l.substring(2).strip().replaceAll("^[\"']|[\"']$", ""));
        }
        return out;
    }

    static List<String> gitLog(String from, String to) {
        try {
            Proc p = run(gitCmd(), "log", "--oneline", from + ".." + to);
            return p.exit == 0 && !p.out.isEmpty() ? p.out : List.of("—");
        } catch (Exception e) { return List.of("—"); }
    }

    static String bar(double fraction) {
        int width = 20;
        int full = (int) Math.round(Math.max(0, Math.min(1, fraction)) * width);
        return "█".repeat(full) + "░".repeat(width - full);
    }

    static String hms(long ms) {
        long s = ms / 1000;
        return s >= 3600 ? String.format(Locale.ROOT, "%dh%02dm%02ds", s / 3600, (s % 3600) / 60, s % 60)
             : s >= 60   ? String.format(Locale.ROOT, "%dm%02ds", s / 60, s % 60)
                         : s + "s";
    }

    static String pct(long part, long whole) {
        return whole <= 0 ? "0%" : Math.round(100.0 * part / whole) + "%";
    }

    static String n(long v) { return String.format(PT, "%,d", v); }

    static String pad(String s, int width) {
        return s.length() >= width ? s.substring(0, width - 1) + " "
                                   : s + " ".repeat(width - s.length());
    }

    static long num(Object o) { return o instanceof Number x ? x.longValue() : 0L; }

    static Double dbl(Object o) { return o instanceof Number x ? x.doubleValue() : null; }

    static String orDash(String s) { return s == null || s.isBlank() ? "—" : s; }

    static String orEmpty(String s) { return s == null ? "" : s; }

    // ── utilities ────────────────────────────────────────────────────────────

    /** Extracts tool_input.file_path from the stdin JSON without an external library. */
    static String filePath(String json) {
        Matcher m = Pattern.compile("\"file_path\"\\s*:\\s*\"((?:[^\"\\\\]|\\\\.)*)\"")
                .matcher(json);
        if (!m.find()) return null;
        String raw = m.group(1)
                .replace("\\\\", "\\").replace("\\\"", "\"").replace("\\/", "/");
        return raw;   // Windows arrives with '\\'; Paths.get handles both separators
    }

    /** Path of the Maven module containing the file, or null if there is no POM. */
    static String moduleOf(String rel) {
        Path p = Paths.get(rel).getParent();
        while (p != null) {
            if (Files.isRegularFile(ROOT.resolve(p).resolve("pom.xml"))) {
                String s = p.toString().replace('\\', '/');
                return s.isEmpty() ? "." : s;
            }
            p = p.getParent();
        }
        return null;
    }

    /** The right wrapper for this operating system — the same problem Maven already solved. */
    static String wrapper() {
        Path w = ROOT.resolve(WINDOWS ? "mvnw.cmd" : "mvnw");
        return Files.isRegularFile(w) ? w.toString() : null;
    }

    static String gitCmd() { return "git"; }

    static String relative(Path abs) {
        try { return ROOT.relativize(abs.toAbsolutePath().normalize())
                        .toString().replace('\\', '/'); }
        catch (Exception e) { return abs.toString().replace('\\', '/'); }
    }

    record Proc(int exit, List<String> out) {}

    static Proc run(String... cmd) throws Exception {
        ProcessBuilder pb = new ProcessBuilder(cmd).directory(ROOT.toFile());
        pb.redirectErrorStream(true);
        Process proc = pb.start();
        List<String> out;
        try (BufferedReader r = new BufferedReader(
                new InputStreamReader(proc.getInputStream(), StandardCharsets.UTF_8))) {
            out = r.lines().collect(Collectors.toList());
        }
        return new Proc(proc.waitFor(), out);
    }

    static String readAll(InputStream in) throws IOException {
        return new String(in.readAllBytes(), StandardCharsets.UTF_8);
    }

    static List<String> tail(List<String> lines, int n) {
        return lines.subList(Math.max(0, lines.size() - n), lines.size());
    }

    static void err(String s) { ERR.println(s); }

    // ── access to already-parsed JSON ───────────────────────────────────────

    @SuppressWarnings("unchecked")
    static Map<String, Object> asMap(Object o) {
        return o instanceof Map ? (Map<String, Object>) o : null;
    }

    @SuppressWarnings("unchecked")
    static List<Object> asList(Object o) {
        return o instanceof List ? (List<Object>) o : List.of();
    }

    static String asStr(Object o) { return o instanceof String ? (String) o : null; }

    static List<String> asStrList(Object o) {
        return asList(o).stream().map(ArchHook::asStr).filter(Objects::nonNull)
                .collect(Collectors.toList());
    }

    static Object get(Object o, String... path) {
        for (String k : path) {
            Map<String, Object> m = asMap(o);
            if (m == null) return null;
            o = m.get(k);
        }
        return o;
    }

    // ── JSON ─────────────────────────────────────────────────────────────────
    //
    // ~50-line recursive parser. Regex over JSON breaks with escaped quotes
    // and nesting — and here we read the runtime's stdin and the user's
    // settings.json, two places where breaking silently is worse than not
    // validating. The dependency remains just the JDK.

    static final class Json {
        private final String s;
        private int i;

        private Json(String s) { this.s = s; }

        /** The top-level value, or null if the text is not valid JSON. */
        static Object parse(String text) {
            if (text == null || text.isBlank()) return null;
            try { Json j = new Json(text); j.ws(); return j.value(); }
            catch (RuntimeException e) { return null; }
        }

        private Object value() {
            ws();
            char c = s.charAt(i);
            return switch (c) {
                case '{' -> obj();
                case '[' -> arr();
                case '"' -> str();
                case 't' -> { i += 4; yield Boolean.TRUE; }
                case 'f' -> { i += 5; yield Boolean.FALSE; }
                case 'n' -> { i += 4; yield null; }
                default  -> num();
            };
        }

        private Map<String, Object> obj() {
            Map<String, Object> m = new LinkedHashMap<>();
            i++; ws();
            if (s.charAt(i) == '}') { i++; return m; }
            while (true) {
                ws();
                String k = str();
                ws(); i++;                                   // ':'
                m.put(k, value());
                ws();
                if (s.charAt(i++) == '}') return m;           // otherwise it was ','
            }
        }

        private List<Object> arr() {
            List<Object> l = new ArrayList<>();
            i++; ws();
            if (s.charAt(i) == ']') { i++; return l; }
            while (true) {
                l.add(value());
                ws();
                if (s.charAt(i++) == ']') return l;           // otherwise it was ','
            }
        }

        private String str() {
            StringBuilder b = new StringBuilder();
            i++;
            while (true) {
                char c = s.charAt(i++);
                if (c == '"') return b.toString();
                if (c != '\\') { b.append(c); continue; }
                char e = s.charAt(i++);
                switch (e) {
                    case 'n' -> b.append('\n');
                    case 't' -> b.append('\t');
                    case 'r' -> b.append('\r');
                    case 'b' -> b.append('\b');
                    case 'f' -> b.append('\f');
                    case 'u' -> {
                        b.append((char) Integer.parseInt(s.substring(i, i + 4), 16));
                        i += 4;
                    }
                    default  -> b.append(e);                 // \" \\ \/
                }
            }
        }

        private Object num() {
            int start = i;
            while (i < s.length() && "-+.eE0123456789".indexOf(s.charAt(i)) >= 0) i++;
            return Double.valueOf(s.substring(start, i));
        }

        private void ws() {
            while (i < s.length() && Character.isWhitespace(s.charAt(i))) i++;
        }
    }
}
