///usr/bin/env java --source 21 "$0" "$@" ; exit $?
//
// ArchHook — project hooks in a single Java file.
//
// Why Java and not bash+PowerShell: this template targets Java developers,
// so the JDK is the only dependency that can be assumed on any operating system.
// Writing the logic twice (.sh and .ps1) would violate the "each rule has a single
// owner" rule this repository enforces everywhere else — and the two copies would drift.
//
// Execution (Java 11+, single-file source): java ArchHook.java <mode>
//   check   PostToolUse — forbidden imports + incremental compile     (blocks)
//   format  PostToolUse — spotless on the touched module              (never blocks)
//   tests   Stop        — tests of the changed modules                (blocks)
//   schema  Pre/PostToolUse + Stop — frontmatter of extension files   (blocks)
//   doctor  manual      — diagnoses the setup on this machine         (never blocks)
//
// Dependencies: JDK. Nothing else.

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import java.util.regex.*;
import java.util.stream.*;

public class ArchHook {

    static final Path ROOT = Paths.get(
            Optional.ofNullable(System.getenv("CLAUDE_PROJECT_DIR")).orElse("."))
            .toAbsolutePath().normalize();
    static final boolean WINDOWS =
            System.getProperty("os.name", "").toLowerCase(Locale.ROOT).contains("win");

    /** Windows consoles default to cp1252: forcing UTF-8 avoids broken accented characters. */
    static final PrintStream ERR = new PrintStream(
            new FileOutputStream(FileDescriptor.err), true, StandardCharsets.UTF_8);

    public static void main(String[] args) throws Exception {
        String mode = args.length > 0 ? args[0] : "check";
        String stdin = readAll(System.in);
        try {
            switch (mode) {
                case "check"  -> check(filePath(stdin));
                case "format" -> format(filePath(stdin));
                case "tests"  -> tests(stdin);
                case "schema" -> schema(stdin);
                case "doctor" -> doctor();
                default -> { err("Unknown mode: " + mode); System.exit(0); }
            }
        } catch (Exception e) {
            // A hook must never crash the session because of its own error.
            err("⚠️  ArchHook (" + mode + ") failed: " + e);
            System.exit(0);
        }
        System.exit(0);
    }

    // ── check ────────────────────────────────────────────────────────────────
    static void check(String file) throws Exception {
        if (file == null || !file.endsWith(".java")) return;
        Path abs = Paths.get(file);
        if (!Files.isRegularFile(abs)) return;
        String rel = relative(abs);

        // 1. forbidden imports
        Path map = ROOT.resolve(".claude/forbidden-imports.txt");
        if (Files.isRegularFile(map)) {
            String src = Files.readString(abs, StandardCharsets.UTF_8);
            List<String> viol = new ArrayList<>();
            for (String line : Files.readAllLines(map, StandardCharsets.UTF_8)) {
                line = line.strip();
                if (line.isEmpty() || line.startsWith("#")) continue;
                int bar = line.indexOf('|');
                if (bar < 0) continue;
                String module = line.substring(0, bar).strip();
                String prefix = line.substring(bar + 1).strip();
                if (prefix.isEmpty() || !rel.startsWith(module + "/")) continue;
                Pattern p = Pattern.compile(
                        "(?m)^\\s*import\\s+(static\\s+)?" + Pattern.quote(prefix));
                if (p.matcher(src).find()) {
                    viol.add("  " + prefix + "  (forbidden in module '" + module + "')");
                }
            }
            if (!viol.isEmpty()) {
                err("❌ Architectural boundary violation — " + rel);
                err("Forbidden imports found:");
                viol.forEach(ArchHook::err);
                err("");
                err("The responsibility is in the wrong module. Move the code, not the rule.");
                err("Rule: .claude/rules/architecture-ddd.md");
                System.exit(2);
            }
        } else {
            err("⚠️  .claude/forbidden-imports.txt does not exist.");
            err("   Boundary enforcement OFF — nothing was checked.");
            err("   This file is generated by /init-project from the active blueprint.");
        }

        // 2. incremental compile of the touched module
        String module = moduleOf(rel);
        if (module == null) return;                       // no POM yet: mid-generation
        String mvnw = wrapper();
        if (mvnw == null) {
            err("⚠️  Maven wrapper missing — compilation NOT checked.");
            err("   Run /init-project (starter.tgz already brings the mvnw).");
            return;
        }
        Proc r = run(mvnw, "-q", "-o", "-pl", module, "-am", "test-compile");
        if (r.exit != 0) {
            err("❌ Compilation failed in " + module);
            tail(r.out, 30).forEach(ArchHook::err);
            System.exit(2);
        }
    }

    // ── format ───────────────────────────────────────────────────────────────
    static void format(String file) throws Exception {
        if (file == null || !file.endsWith(".java")) return;
        Path abs = Paths.get(file);
        if (!Files.isRegularFile(abs)) return;
        String module = moduleOf(relative(abs));
        String mvnw = wrapper();
        if (module == null || mvnw == null) return;
        run(mvnw, "-q", "-o", "-pl", module, "spotless:apply");   // failure is ignored
    }

    // ── tests ────────────────────────────────────────────────────────────────
    static void tests(String stdin) throws Exception {
        // If the Stop hook already blocked before, don't block again: avoids cycles.
        if (Pattern.compile("\"stop_hook_active\"\\s*:\\s*true").matcher(stdin).find()) return;

        String mvnw = wrapper();
        if (mvnw == null) return;

        Proc diff = run(gitCmd(), "diff", "--name-only", "HEAD");
        Proc untracked = run(gitCmd(), "ls-files", "--others", "--exclude-standard");
        if (diff.exit != 0 && untracked.exit != 0) return;        // no git or no HEAD

        Set<String> modules = Stream.concat(diff.out.stream(), untracked.out.stream())
                .filter(f -> f.endsWith(".java"))
                .map(ArchHook::moduleOf)
                .filter(Objects::nonNull)
                .collect(Collectors.toCollection(LinkedHashSet::new));
        if (modules.isEmpty()) return;

        String list = String.join(",", modules);
        err("▶ Tests for affected modules: " + list);
        Proc r = run(mvnw, "-q", "-o", "-pl", list, "-am", "test");
        if (r.exit != 0) {
            err("❌ Tests failed");
            List<String> relevant = r.out.stream()
                    .filter(l -> l.matches(".*(ERROR|FAIL|Tests run).*"))
                    .collect(Collectors.toList());
            tail(relevant.isEmpty() ? r.out : relevant, 25).forEach(ArchHook::err);
            System.exit(2);
        }
        err("✅ Tests green");
    }

    // ── doctor ───────────────────────────────────────────────────────────────
    /** Answers "does this work on my machine?" without having to guess. */
    static void doctor() {
        err("ArchHook doctor");
        err("  OS ................ " + System.getProperty("os.name")
                + (WINDOWS ? "  (Windows — no shell is used, exec form)" : ""));
        err("  Java .............. " + System.getProperty("java.version"));
        err("  Project root ...... " + ROOT);
        report("CLAUDE_PROJECT_DIR", System.getenv("CLAUDE_PROJECT_DIR") != null,
                "set", "NOT set — hooks use the current directory");
        String w = wrapper();
        report("Maven wrapper", w != null, w == null ? "" : w,
                "missing — run /init-project (starter.tgz already brings the mvnw)");
        Path map = ROOT.resolve(".claude/forbidden-imports.txt");
        long rules = 0;
        try {
            if (Files.isRegularFile(map)) {
                rules = Files.readAllLines(map).stream()
                        .map(String::strip)
                        .filter(l -> !l.isEmpty() && !l.startsWith("#") && l.contains("|"))
                        .count();
            }
        } catch (IOException ignored) { }
        report("Boundaries", rules > 0, rules + " active rules",
                "0 rules — ENFORCEMENT OFF. Generated by /init-project");
        long badSchema = -1;
        if (Files.isRegularFile(ROOT.resolve(SCHEMA_FILE))) {
            List<String> errs = new ArrayList<>();
            try {
                sweep(asMap(Json.parse(readOrNull(ROOT.resolve(SCHEMA_FILE)))), errs);
                badSchema = errs.size();
            } catch (IOException ignored) { }
        }
        report("Schema", badSchema == 0,
                "all extension files pass",
                badSchema < 0 ? "no " + SCHEMA_FILE + " — validation OFF"
                              : badSchema + " files with invalid frontmatter");
        boolean git = false;
        try { git = run("git", "rev-parse", "HEAD").exit == 0; } catch (Exception ignored) { }
        report("git HEAD", git, "exists",
                "no commits — the tests hook does not run (git diff HEAD fails)");
        err("");
        err(rules > 0 && w != null
                ? "✅ Setup operational."
                : "⚠️  Setup incomplete — see marked lines above.");
    }

    static void report(String label, boolean ok, String yes, String no) {
        String pad = "                  ".substring(Math.min(label.length(), 17));
        err("  " + label + " " + pad.replace(' ', '.') + " " + (ok ? "✅ " + yes : "❌ " + no));
    }

    // ── schema ───────────────────────────────────────────────────────────────
    //
    // Guards the frontmatter fields of Claude Code's extension files.
    // The runtime silently ignores an unknown field and `claude plugin validate`
    // lets it through: without this mode, a wrong field looks like behavior and is
    // just decoration. The field list does NOT live here — it lives in
    // .claude/schemas/extensions.json, so that adding a field doesn't require
    // touching Java. Rationale and design:
    // .claude/decisions/0001-schema-frontmatter-extensions.md

    static final String SCHEMA_FILE = ".claude/schemas/extensions.json";

    static void schema(String stdin) throws Exception {
        // If the Stop hook already blocked before, don't block again: avoids cycles.
        if (Pattern.compile("\"stop_hook_active\"\\s*:\\s*true").matcher(stdin).find()) return;

        Map<String, Object> sch = asMap(Json.parse(readOrNull(ROOT.resolve(SCHEMA_FILE))));
        if (sch == null) {
            err("⚠️  " + SCHEMA_FILE + " missing or invalid.");
            err("   Frontmatter validation OFF — nothing was checked.");
            return;
        }

        Map<String, Object> in = asMap(get(Json.parse(stdin), "tool_input"));
        String file = in != null ? asStr(in.get("file_path")) : filePath(stdin);

        List<String> errors = new ArrayList<>();
        if (file == null) {
            sweep(sch, errors);                       // Stop, or manual invocation
        } else {
            String rel = relative(Paths.get(file));
            // Write brings the whole file in tool_input.content and is validated before
            // writing. Edit brings old_string/new_string — there only disk works.
            String content = in != null ? asStr(in.get("content")) : null;
            if (content == null) content = readOrNull(Paths.get(file));
            if (content == null) return;              // file deleted or unreadable
            checkOne(sch, rel, content, errors);
        }

        if (!errors.isEmpty()) {
            err("❌ Invalid frontmatter — " + errors.size()
                    + (errors.size() == 1 ? " problem" : " problems"));
            errors.forEach(ArchHook::err);
            err("");
            err("Valid fields by type: " + SCHEMA_FILE);
            err("What each field is for: .claude/skills/claude-code-architect-designer"
                    + "/references/frontmatter-fields.md");
            System.exit(2);
        }
    }

    /** Sweeps every file that some schema `match` captures. */
    static void sweep(Map<String, Object> sch, List<String> errors) throws IOException {
        List<String> globs = new ArrayList<>();
        Map<String, Object> types = asMap(sch.get("types"));
        if (types != null) {
            for (Object t : types.values()) {
                String g = asStr(asMap(t) == null ? null : asMap(t).get("match"));
                if (g != null) globs.add(g);
            }
        }
        String sg = asStr(get(sch, "settings", "match"));
        if (sg != null) globs.add(sg);

        for (String g : globs) {
            Path base = ROOT.resolve(g.substring(0, Math.max(0, g.indexOf('*'))))
                    .normalize();
            if (!Files.isDirectory(base)) {
                if (Files.isRegularFile(base)) {       // glob without `*`: settings.json
                    checkOne(sch, relative(base), readOrNull(base), errors);
                }
                continue;
            }
            Pattern re = glob(g);
            try (Stream<Path> walk = Files.walk(base)) {
                List<Path> hits = walk.filter(Files::isRegularFile)
                        .filter(f -> re.matcher(relative(f)).matches())
                        .sorted().collect(Collectors.toList());
                for (Path f : hits) checkOne(sch, relative(f), readOrNull(f), errors);
            }
        }
    }

    /** Validates one file. A path that no `match` captures exits silently. */
    static void checkOne(Map<String, Object> sch, String rel, String content,
                         List<String> errors) {
        if (content == null) return;

        if (matches(asStr(get(sch, "settings", "match")), rel)) {
            checkSettings(sch, rel, content, errors);
            return;
        }

        Map<String, Object> types = asMap(sch.get("types"));
        if (types == null) return;
        for (Map.Entry<String, Object> e : types.entrySet()) {
            Map<String, Object> t = asMap(e.getValue());
            if (t == null || !matches(asStr(t.get("match")), rel)) continue;
            checkFrontmatter(sch, e.getKey(), t, rel, content, errors);
            return;
        }
    }

    static void checkFrontmatter(Map<String, Object> sch, String type,
                                 Map<String, Object> t, String rel, String content,
                                 List<String> errors) {
        Map<String, String> fm = frontmatter(content);
        if (fm == null) {
            errors.add("  " + rel + " — no frontmatter block closed by `---`"
                    + " (type '" + type + "')");
            return;
        }

        for (String req : asStrList(t.get("required"))) {
            if (!fm.containsKey(req)) {
                errors.add("  " + rel + " — missing required field `" + req + "`");
            }
        }

        List<String> allowed = asStrList(t.get("allowed"));
        List<String> forbidden = asStrList(sch.get("forbidden_everywhere"));
        for (String key : fm.keySet()) {
            if (forbidden.contains(key)) {
                errors.add("  " + rel + " — `" + key + "` is not a native field."
                        + " What it used to carry lives in the `## Contrato` section of the body");
                continue;
            }
            if (allowed.contains(key)) continue;
            String hint = nearest(key, allowed);
            errors.add("  " + rel + " — `" + key + "` is not a field of '" + type + "'"
                    + (hint != null
                        ? ". It is written `" + hint + "` (skills use kebab-case,"
                          + " agents use camelCase)"
                        : ". The runtime silently ignores it"));
        }

        Map<String, Object> enums = asMap(t.get("enum"));
        if (enums == null) return;
        for (Map.Entry<String, Object> e : enums.entrySet()) {
            String v = fm.get(e.getKey());
            List<String> ok = asStrList(e.getValue());
            if (v == null || v.isEmpty() || ok.contains(v)) continue;
            errors.add("  " + rel + " — `" + e.getKey() + ": " + v + "` invalid."
                    + " Values: " + String.join(", ", ok));
        }
    }

    /** Validates each hook entry of settings.json, in any event. */
    static void checkSettings(Map<String, Object> sch, String rel, String content,
                              List<String> errors) {
        Map<String, Object> root = asMap(Json.parse(content));
        if (root == null) { errors.add("  " + rel + " — invalid JSON"); return; }
        Map<String, Object> hooks = asMap(root.get("hooks"));
        if (hooks == null) return;

        List<String> req = asStrList(get(sch, "settings", "hook_entry", "required"));
        List<String> allowed = asStrList(get(sch, "settings", "hook_entry", "allowed"));

        for (Map.Entry<String, Object> ev : hooks.entrySet()) {
            for (Object group : asList(ev.getValue())) {
                Map<String, Object> g = asMap(group);
                if (g == null) continue;
                for (Object entry : asList(g.get("hooks"))) {
                    Map<String, Object> h = asMap(entry);
                    if (h == null) continue;
                    String where = rel + " › " + ev.getKey();
                    for (String r : req) {
                        if (!h.containsKey(r)) {
                            errors.add("  " + where + " — hook entry missing `" + r + "`");
                        }
                    }
                    for (String k : h.keySet()) {
                        if (!allowed.contains(k)) {
                            errors.add("  " + where + " — `" + k
                                    + "` is not a hook entry field");
                        }
                    }
                }
            }
        }
    }

    /**
     * Top-level frontmatter keys and their scalar value, in file order. Returns
     * null when there is no closed `---` block. No YAML library: only unindented
     * keys matter. `#` comments are ignored — two rules in this repo use them
     * inside frontmatter.
     */
    static Map<String, String> frontmatter(String content) {
        List<String> lines = content.lines().collect(Collectors.toList());
        int start = -1;
        for (int i = 0; i < lines.size(); i++) {
            String l = lines.get(i).strip();
            if (l.isEmpty()) continue;
            if (l.equals("---")) start = i;
            break;
        }
        if (start < 0) return null;

        Map<String, String> fm = new LinkedHashMap<>();
        for (int i = start + 1; i < lines.size(); i++) {
            String raw = lines.get(i);
            if (raw.strip().equals("---")) return fm;
            if (raw.isBlank() || raw.stripLeading().startsWith("#")) continue;
            if (Character.isWhitespace(raw.charAt(0)) || raw.startsWith("-")) continue;
            int c = raw.indexOf(':');
            if (c <= 0) continue;
            String v = raw.substring(c + 1).strip();
            if (v.startsWith(">") || v.startsWith("|")) v = "";   // block scalar
            fm.put(raw.substring(0, c).strip(), v);
        }
        return null;                                  // block opened and never closed
    }

    /** The allowed field that only differs in naming convention, or null. */
    static String nearest(String key, List<String> allowed) {
        String n = key.toLowerCase(Locale.ROOT).replace("-", "").replace("_", "");
        for (String a : allowed) {
            if (a.toLowerCase(Locale.ROOT).replace("-", "").replace("_", "").equals(n)) {
                return a;
            }
        }
        return null;
    }

    static boolean matches(String globPattern, String rel) {
        return globPattern != null && glob(globPattern).matcher(rel).matches();
    }

    /** Glob to regex: `**` crosses `/`, `*` does not. */
    static Pattern glob(String g) {
        StringBuilder b = new StringBuilder("^");
        for (int i = 0; i < g.length(); i++) {
            char c = g.charAt(i);
            if (c == '*') {
                if (i + 1 < g.length() && g.charAt(i + 1) == '*') { b.append(".*"); i++; }
                else b.append("[^/]*");
            } else if (c == '?') {
                b.append("[^/]");
            } else {
                b.append(Pattern.quote(String.valueOf(c)));
            }
        }
        return Pattern.compile(b.append("$").toString());
    }

    static String readOrNull(Path p) {
        try { return Files.isRegularFile(p)
                ? Files.readString(p, StandardCharsets.UTF_8) : null; }
        catch (IOException e) { return null; }
    }

    // ── utilities ────────────────────────────────────────────────────────────

    /** Extracts tool_input.file_path from the stdin JSON without an external library. */
    static String filePath(String json) {
        Matcher m = Pattern.compile("\"file_path\"\\s*:\\s*\"((?:[^\"\\\\]|\\\\.)*)\"")
                .matcher(json);
        if (!m.find()) return null;
        String raw = m.group(1)
                .replace("\\\\", "\\").replace("\\\"", "\"").replace("\\/", "/");
        return raw;   // Windows arrives with '\\'; Paths.get handles both separators
    }

    /** Path of the Maven module containing the file, or null if there is no POM. */
    static String moduleOf(String rel) {
        Path p = Paths.get(rel).getParent();
        while (p != null) {
            if (Files.isRegularFile(ROOT.resolve(p).resolve("pom.xml"))) {
                String s = p.toString().replace('\\', '/');
                return s.isEmpty() ? "." : s;
            }
            p = p.getParent();
        }
        return null;
    }

    /** The right wrapper for this operating system — the same problem Maven already solved. */
    static String wrapper() {
        Path w = ROOT.resolve(WINDOWS ? "mvnw.cmd" : "mvnw");
        return Files.isRegularFile(w) ? w.toString() : null;
    }

    static String gitCmd() { return "git"; }

    static String relative(Path abs) {
        try { return ROOT.relativize(abs.toAbsolutePath().normalize())
                        .toString().replace('\\', '/'); }
        catch (Exception e) { return abs.toString().replace('\\', '/'); }
    }

    record Proc(int exit, List<String> out) {}

    static Proc run(String... cmd) throws Exception {
        ProcessBuilder pb = new ProcessBuilder(cmd).directory(ROOT.toFile());
        pb.redirectErrorStream(true);
        Process proc = pb.start();
        List<String> out;
        try (BufferedReader r = new BufferedReader(
                new InputStreamReader(proc.getInputStream(), StandardCharsets.UTF_8))) {
            out = r.lines().collect(Collectors.toList());
        }
        return new Proc(proc.waitFor(), out);
    }

    static String readAll(InputStream in) throws IOException {
        return new String(in.readAllBytes(), StandardCharsets.UTF_8);
    }

    static List<String> tail(List<String> lines, int n) {
        return lines.subList(Math.max(0, lines.size() - n), lines.size());
    }

    static void err(String s) { ERR.println(s); }

    // ── access to already-parsed JSON ───────────────────────────────────────

    @SuppressWarnings("unchecked")
    static Map<String, Object> asMap(Object o) {
        return o instanceof Map ? (Map<String, Object>) o : null;
    }

    @SuppressWarnings("unchecked")
    static List<Object> asList(Object o) {
        return o instanceof List ? (List<Object>) o : List.of();
    }

    static String asStr(Object o) { return o instanceof String ? (String) o : null; }

    static List<String> asStrList(Object o) {
        return asList(o).stream().map(ArchHook::asStr).filter(Objects::nonNull)
                .collect(Collectors.toList());
    }

    static Object get(Object o, String... path) {
        for (String k : path) {
            Map<String, Object> m = asMap(o);
            if (m == null) return null;
            o = m.get(k);
        }
        return o;
    }

    // ── JSON ─────────────────────────────────────────────────────────────────
    //
    // ~50-line recursive parser. Regex over JSON breaks with escaped quotes
    // and nesting — and here we read the runtime's stdin and the user's
    // settings.json, two places where breaking silently is worse than not
    // validating. The dependency remains just the JDK.

    static final class Json {
        private final String s;
        private int i;

        private Json(String s) { this.s = s; }

        /** The top-level value, or null if the text is not valid JSON. */
        static Object parse(String text) {
            if (text == null || text.isBlank()) return null;
            try { Json j = new Json(text); j.ws(); return j.value(); }
            catch (RuntimeException e) { return null; }
        }

        private Object value() {
            ws();
            char c = s.charAt(i);
            return switch (c) {
                case '{' -> obj();
                case '[' -> arr();
                case '"' -> str();
                case 't' -> { i += 4; yield Boolean.TRUE; }
                case 'f' -> { i += 5; yield Boolean.FALSE; }
                case 'n' -> { i += 4; yield null; }
                default  -> num();
            };
        }

        private Map<String, Object> obj() {
            Map<String, Object> m = new LinkedHashMap<>();
            i++; ws();
            if (s.charAt(i) == '}') { i++; return m; }
            while (true) {
                ws();
                String k = str();
                ws(); i++;                                   // ':'
                m.put(k, value());
                ws();
                if (s.charAt(i++) == '}') return m;           // otherwise it was ','
            }
        }

        private List<Object> arr() {
            List<Object> l = new ArrayList<>();
            i++; ws();
            if (s.charAt(i) == ']') { i++; return l; }
            while (true) {
                l.add(value());
                ws();
                if (s.charAt(i++) == ']') return l;           // otherwise it was ','
            }
        }

        private String str() {
            StringBuilder b = new StringBuilder();
            i++;
            while (true) {
                char c = s.charAt(i++);
                if (c == '"') return b.toString();
                if (c != '\\') { b.append(c); continue; }
                char e = s.charAt(i++);
                switch (e) {
                    case 'n' -> b.append('\n');
                    case 't' -> b.append('\t');
                    case 'r' -> b.append('\r');
                    case 'b' -> b.append('\b');
                    case 'f' -> b.append('\f');
                    case 'u' -> {
                        b.append((char) Integer.parseInt(s.substring(i, i + 4), 16));
                        i += 4;
                    }
                    default  -> b.append(e);                 // \" \\ \/
                }
            }
        }

        private Object num() {
            int start = i;
            while (i < s.length() && "-+.eE0123456789".indexOf(s.charAt(i)) >= 0) i++;
            return Double.valueOf(s.substring(start, i));
        }

        private void ws() {
            while (i < s.length() && Character.isWhitespace(s.charAt(i))) i++;
        }
    }
}
