///usr/bin/env java --source 21 "$0" "$@" ; exit $?
//
// CI test: proves the transport templates `transport-security-setup` writes into a project
// still do what they claim, in a fresh Initializr project, once per topology:
//   - topology A (edge): `application-tls-edge.yml.example` + `HstsHeaderFilter` +
//     `ForwardedHeadersIT` — HSTS only from a trusted proxy, h2c behind the edge;
//   - topology B (direct): `application-tls-direct.yml.example` + `HstsHeaderFilter` +
//     `TransportSecurityIT` — HTTP/2 over TLS 1.3, TLS 1.2 accepted, HSTS, the certificate
//     generated by the JDK's keytool when the test runs.
//
// Why it exists: these files are copied, not read as shape references, and what they claim is
// runtime behaviour no review can see — a bundle that fails the startup when its file is absent
// (the reason the TLS block sits in a profile-gated document), a forwarded scheme honoured only
// from the trusted list, a header the security chain's writer skips when it is already there.
// Each claim was proven green and red by hand when the templates were written (decision 0122);
// this test keeps the green half from rotting on the next Boot release.
//
// Same shape as JavaTemplatesTest: a real project from start.spring.io with the Java version of
// the JDK running it, never a versioned fixture; the templates read from disk on every run.

import java.io.*;
import java.net.URI;
import java.net.http.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import java.util.regex.*;
import java.util.zip.*;

public class TransportTemplatesTest {

    static final Path TEMPLATES = Paths.get(".claude/skills/transport-security-setup/templates");
    static final Pattern PACKAGE = Pattern.compile("(?m)^package\\s+([\\w.]+)\\s*;");
    static final String BASE_YML = "spring:\n  application:\n    name: minhaapi\n\n";

    public static void main(String[] args) throws Exception {
        int failures = 0;
        failures += topology("A · edge", "application-tls-edge.yml.example", "ForwardedHeadersIT");
        failures += topology("B · direct", "application-tls-direct.yml.example", "TransportSecurityIT");
        if (failures > 0) {
            System.out.println("❌ " + failures + " topology(ies) failed — a transport template no longer proves its claim.");
            System.exit(1);
        }
        System.out.println("✅ Both topologies: the configuration, HstsHeaderFilter and the transport IT pass in a fresh Initializr project.");
    }

    static int topology(String label, String yml, String it) throws Exception {
        Path app = initializrProject(Files.createTempDirectory("transport-templates-test"));
        Files.writeString(app.resolve("src/main/resources/application.yml"),
                BASE_YML + read(yml), StandardCharsets.UTF_8);
        Files.deleteIfExists(app.resolve("src/main/resources/application.properties"));
        place(app, "src/main/java", "HstsHeaderFilter", read("HstsHeaderFilter.java.example"));
        place(app, "src/test/java", it, read(it + ".java.example"));

        List<String> cmd = List.of(app.resolve("mvnw").toString(), "-B", "-q", "test",
                "-Dtest=" + it + "*", "-Dsurefire.failIfNoSpecifiedTests=false");
        Process p = new ProcessBuilder(cmd).directory(app.toFile()).redirectErrorStream(true).start();
        String out = new String(p.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
        int exit = p.waitFor();
        if (exit != 0) {
            System.out.println(tail(out, 60));
            System.out.println("❌ " + label + ": `./mvnw test -Dtest=" + it + "*` exited " + exit
                    + ". A compile error names the template by its class; a failed case names the claim.");
            return 1;
        }
        System.out.println("✅ " + label + ": " + yml + " + HstsHeaderFilter + " + it + " pass.");
        return 0;
    }

    /** start.spring.io, same source `project-bootstrap` step 3 uses; web and actuator, as generated. */
    static Path initializrProject(Path work) throws Exception {
        int java = Runtime.version().feature();
        String url = "https://start.spring.io/starter.zip?type=maven-project&language=java"
                + "&dependencies=web,actuator&groupId=com.exemplo&artifactId=minhaapi&name=minhaapi"
                + "&packageName=com.exemplo.minhaapi&baseDir=app&javaVersion=" + java;
        HttpResponse<InputStream> r = HttpClient.newBuilder().followRedirects(HttpClient.Redirect.NORMAL).build()
                .send(HttpRequest.newBuilder(URI.create(url)).build(), HttpResponse.BodyHandlers.ofInputStream());
        if (r.statusCode() != 200) fail("HTTP " + r.statusCode() + " from start.spring.io: " + url);
        try (ZipInputStream zip = new ZipInputStream(r.body())) {
            for (ZipEntry e; (e = zip.getNextEntry()) != null; ) {
                Path target = work.resolve(e.getName()).normalize();
                if (!target.startsWith(work)) fail("zip entry escapes the work dir: " + e.getName());
                if (e.isDirectory()) Files.createDirectories(target);
                else {
                    Files.createDirectories(target.getParent());
                    Files.copy(zip, target, StandardCopyOption.REPLACE_EXISTING);
                }
            }
        }
        Path app = work.resolve("app");
        if (!app.resolve("mvnw").toFile().setExecutable(true)) fail("could not mark mvnw executable");
        return app;
    }

    static String read(String template) throws IOException {
        return Files.readString(TEMPLATES.resolve(template), StandardCharsets.UTF_8);
    }

    /** Under the directory the template's own `package` line names. */
    static void place(Path app, String root, String className, String source) throws IOException {
        Matcher m = PACKAGE.matcher(source);
        if (!m.find()) fail(className + ": no package declaration");
        Path file = app.resolve(root).resolve(m.group(1).replace('.', '/')).resolve(className + ".java");
        Files.createDirectories(file.getParent());
        Files.writeString(file, source, StandardCharsets.UTF_8);
    }

    static String tail(String s, int lines) {
        List<String> all = s.lines().toList();
        return String.join("\n", all.subList(Math.max(0, all.size() - lines), all.size()));
    }

    static void fail(String message) {
        System.out.println("❌ " + message);
        System.exit(1);
    }
}
